### ISSUE TITLE
Sockets = NativeModules.TcpSockets Undefined

### ISSUE THREAD

**Issue by xaviercobain88** [PeelTechnologies/react-native-tcp#1]
Hi please help me,

I'm trying to use your lib but, an undefined appears when the line `var Sockets = NativeModules.TcpSockets;` is executed, I added the native library to ios project and link the library but nothing happends, what can I do?

Thanks a lot

**Comment by aprock** [comment]
is the rctsockets example working for you?

**Comment by xaviercobain88** [comment]
Yeah, example works great, but when I'm using the module on another project it breaks, with trace:
`TypeError: Cannot read property 'connect' of undefined
    at TcpSocket.connect (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81485:8)
    at Object.exports.connect.exports.createConnection (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81327:33)
    at new TcpConnection (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:80992:20)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81287:8
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81302:8
    at tryCatcher (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:88621:15)
    at Promise._resolveFromResolver (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:86700:25)
    at new Promise (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:86290:29)
    at Function.<anonymous> (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81282:8)
    at Function.connect (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:82639:12)
    at new Login (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:66448:3)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:13844:6)
    at wrapper [as mountComponent] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:3221:13)
    at Object.ReactReconciler.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:12392:29)
    at ReactMultiChild.Mixin.mountChildren (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:24905:32)
    at ReactNativeBaseComponent.Mixin.initializeChildren (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:24516:22)`

**Comment by xaviercobain88** [comment]
Is there another setup? on example is not necessary to link library because it is already setup

**Comment by aprock** [comment]
Did you use react-native init to create your ios project? If not, are you linking to libReact and libRCTNetworking?

**Comment by xaviercobain88** [comment]
Seems like the problem is for nested node_modules but now I have this:

`socket-0 connecting, host: rdb.com port: 28015
TcpSocket.js:67socket-0 received connect
TcpSocket.js:67socket-0 received error
TcpSocket.js:67socket-0 destroying
Login.js:15ReqlDriverError {name: "ReqlDriverError", msg: "Could not connect to rdb.com:28015.↵Socket is not connected", frames: undefined, message: "Could not connect to rdb.com:28015.↵Socket is not connected", stack: "ReqlDriverError: Could not connect to rdb.com:2801…1/index.ios.bundle?platform=ios&dev=true:3221:13)"…}__stackCleaned__: trueframes: undefinedmessage: "Could not connect to rdb.com:28015.↵Socket is not connected"msg: "Could not connect to rdb.com:28015.↵Socket is not connected"name: "ReqlDriverError"stack: "ReqlDriverError: Could not connect to rdb.com:28015.↵Socket is not connected↵    at ReqlDriverError.ReqlError [as constructor] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:82918:7)↵    at new ReqlDriverError (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:82963:46)↵    at TcpConnection.<anonymous> (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:80663:17)↵    at TcpConnection.g (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81992:10)↵    at TcpConnection.EventEmitter.emit (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81908:9)↵    at TcpSocket.<anonymous> (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81137:14)↵    at TcpSocket.EventEmitter.emit (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81923:14)↵    at TcpSocket._onError (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81709:6)↵    at EventEmitter.emit (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:4240:23)↵    at MessageQueue.__callFunction (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:2759:23)↵    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:2663:8↵    at guard (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:2617:1)↵    at MessageQueue.callFunctionReturnFlushedQueue (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:2662:1)↵    at DedicatedWorkerGlobalScope.onmessage (http://localhost:8081/debuggerWorker.js:39:56)↵From previous event:↵    at Function.<anonymous> (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:81369:8)↵    at Function.connect (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:82726:12)↵    at new Login (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:66507:3)↵    at ReactCompositeComponentMixin.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:13844:6)↵    at wrapper [as mountComponent] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:3221:13)↵    at Object.ReactReconciler.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:12392:29)↵    at ReactMultiChild.Mixin.mountChildren (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:24905:32)↵    at ReactNativeBaseComponent.Mixin.initializeChildren (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:24516:22)↵    at ReactNativeBaseComponent.Mixin.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:24639:6)↵    at Object.ReactReconciler.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:12392:29)↵    at ReactCompositeComponentMixin.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:13921:28)↵    at wrapper [as mountComponent] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:3221:13)↵    at Object.ReactReconciler.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:12392:29)↵    at ReactMultiChild.Mixin.mountChildren (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:24905:32)↵    at ReactNativeBaseComponent.Mixin.initializeChildren (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:24516:22)↵    at ReactNativeBaseComponent.Mixin.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:24639:6)↵    at Object.ReactReconciler.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:12392:29)↵    at ReactCompositeComponentMixin.mountComponent (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:13921:28)↵    at wrapper [as mountComponent] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:3221:13)"__proto__: ctor`

The socket is closed and no reason

**Comment by mckn** [comment]
I am having the same problem running on react native 0.22.2

**Comment by mckn** [comment]
Fixed my issue by removed all references in XCode to the project and then running rnpm link again.

**Comment by aprock** [comment]
interesting, I haven't played with rnpm link...maybe the readme needs updated?

**Comment by mckn** [comment]
It failed again on one of my colleauges computer and solved it by clearing the derived data like this: http://stackoverflow.com/a/18933382

Might be something to add to the readme?

**Comment by aprock** [comment]
I've updated the documentation and dependencies, this should work now.

**Comment by RenderCoder** [comment]
Same problem. Use the latest version.
