### ISSUE TITLE
setTimeout() not reset when data is received

### ISSUE THREAD

**Issue by joefocusrite** [PeelTechnologies/react-native-tcp#10]
If you call `setTimeout()` on a socket, you expect the timer to be reset whenever there is data. At present, when data is received within timeout period, `clearTimeout()` is called but is never re-submitted:

```
if (this._timeout) {
  clearTimeout(this._timeout);
  this._timeout = null;
}
```

react-native-tcp@1.0.1

**Comment by joefocusrite** [comment]
Is it possible for it to call settimeout on the underlying socket?

**Comment by aprock** [comment]
@joefocusrite agreed, this should be the behavior.
