### ISSUE TITLE
How to connect to ipv6 server?

### ISSUE THREAD

**Issue by richfisher** [PeelTechnologies/react-native-tcp#11]
I'm connecting ipv4 server with

```
var net = require('react-native-tcp');
var client = new net.Socket();
client.connect('port', 'ipv4-address', function() {});
// client = net.createConnection('port', 'address')
```

However, it's not work when I try to connect to ipv6 server.

What's the proper way to connect the socket server? thanks!

**Comment by aprock** [comment]
thanks for the PR!

**Comment by Ethan0007** [comment]
Hi,

any update on this issue?

#Thanks
