### ISSUE TITLE
Can't connect from external client

### ISSUE THREAD

**Issue by franrios** [PeelTechnologies/react-native-tcp#13]
'm trying to serve files from a React-Native app. Im using react-native-tcp module but when I create a TCP server it isn't on a nmap output over the mobile device ip address. I've tried with an external client with nodejs but I get ECONNREFUSED. At the same time, If I try with a client inside the react-native app and an external server, I get the same result.

I don't know if there's a protection or the module doesn't work properly. I've also the android.permission.INTERNET in the manifest.

I'm using a simplified version of the [example](https://github.com/PeelTechnologies/react-native-tcp/blob/master/examples/rctsockets/index.android.js)

**Comment by aprock** [comment]
The module adds the internet permission.  Is this in an emulator? Can you post the full log message?

**Comment by franrios** [comment]
No, it isn't. I'm using a real device connected through ADB. There's no error output. The problem is that when I run a curl command from inside of the device (using adb shell) I get the result that I want but I can't make successful requests from anywhere. I think that the key of the question is that Android is blocking that port. 

Summing up:

`curl IP:PORT` from adb shell works
`curl IP:PORT` from my pc terminal (being in the same network) don't work.

**Comment by aprock** [comment]
you might try again with 2.0.4
https://github.com/PeelTechnologies/react-native-tcp/commit/7f33dfbfff71675a4e81f0548158b5f341f398f6

could have been the issue.
