### ISSUE TITLE
How to make a TLS/SSL connection

### ISSUE THREAD

**Issue by richfisher** [PeelTechnologies/react-native-tcp#15]
I can connect to server with `var client = net.createConnection({port: 'my_port', host: 'my_host'});`

How to adjust the code to connect with TLS? Could you provide an example?

Thanks in advance.

**Comment by aprock** [comment]
tls/ssl is a bit outside the scope of this package.  This is meant to be an api compatible package of node.js's net.

However, the node.js tls implementation is built upon the 'net' package.  So, it's probably a good starting point.
https://github.com/nodejs/node/blob/master/lib/tls.js
