### ISSUE TITLE
Not working with ios10

### ISSUE THREAD

**Issue by em222iv** [PeelTechnologies/react-native-tcp#16]
My project fails when updating to ios10 and xcode 8.

as seen in the pictures:

![skarmavbild 2016-09-19 kl 18 10 46](https://cloud.githubusercontent.com/assets/5379414/18639517/81c640fe-7e94-11e6-8ced-103c4c1be4bd.png)
![skarmavbild 2016-09-19 kl 18 10 56](https://cloud.githubusercontent.com/assets/5379414/18639516/81b2dfaa-7e94-11e6-969e-82023717fef3.png)

**Comment by aprock** [comment]
should be fixed via https://github.com/PeelTechnologies/react-native-tcp/pull/14
deployed as v2.0.2
