### ISSUE TITLE
Can I use pipe with this library?

### ISSUE THREAD

**Issue by jsdario** [PeelTechnologies/react-native-tcp#17]
I am trying to mock an HTTP server to share mp3 files. For that I have the following code:

``` javascript
     socket.on('data', (data) => {
       RNFetchBlob.fs.readStream('/sdcard/Audio/tone.mp3', 'base64')
           .then((stream) => {
             stream.open()
             let data = new Buffer()
             stream.open()
             stream.onData((chunk) => {
                data.concat([data, chunk])
             })
             stream.onEnd(() => {
                socket.write(data)
                socket.end()
             })
         })
```

But it is not working :(
Can I just use pipe? Is there anyone so kind to provide with an example?

Thank you so much.

Update: someone opened a question on stackoverflow about the same thing https://github.com/PeelTechnologies/react-native-tcp/issues/17

**Comment by aprock** [comment]
stream support is a WiP

**Comment by jsdario** [comment]
Ok, I would be happy to help if I can, so feel free to publish a Roadmap.

**Comment by aprock** [comment]
to be clear: basic stream support was added in 3.0, and your example above should work.  I just haven't had the time to test it.

**Comment by jsdario** [comment]
Thanks, if I find myself working on this package any time soon I'll verify it is working and come back to you.

**Comment by aprock** [comment]
tested and verified piping.
closing this issue.
