### ISSUE TITLE
Requiring a non-react-native module that requires net

### ISSUE THREAD

**Issue by paulondc** [PeelTechnologies/react-native-tcp#2]
Hi,

I'm trying to use this module in my project, but I'm facing the following issue:

I've a react-native project that imports a client module which is responsible for doing the requests. This client module works fine in vanilla nodejs, but when I try to use that in conjunction with react-native where react-native-tcp brings the net functionality to react-native, it throws an error telling: "Requiring unknown module 'net'". This occurs when a module inside of the client tries to import 'net'.  

I wonder if you have any suggestions for this issue.

Cheers

**Comment by aprock** [comment]
you might take a look at [rn-nodeify](https://github.com/mvayngrib/rn-nodeify)

**Comment by paulondc** [comment]
Thanks for your reply, unfortunately that module does not seem to be polished for production yet, I'm inclined to refactor my code, by using fetch for all requests and getting rid of dependencies that require the net module, leaving behind only react-native's fetch and node-fetch in the nodejs side (back to the drawing board).

Cheers
