### ISSUE TITLE
TcpServer listening problem in iOS

### ISSUE THREAD

**Issue by jmc420** [PeelTechnologies/react-native-tcp#23]
Hi

I have put together a simple tcp server and client example here:

https://github.com/jmc420/react-native-examples/blob/master/TcpServerProblem/README.md

Everything works well in android but in an iOS environment, the Tcp server stops listening after a client disconnects and will not accept any further connections.

**Comment by aprock** [comment]
thanks for doing all this footwork, i'm investigating this issue further.

**Comment by aprock** [comment]
@JasonMore #28 should fix this issue. would you be able to try it out?

**Comment by JasonMore** [comment]
@aprock @jmc420 This fix works great thanks! I spent some time yesterday trying to figure it out myself, but glad you were able to fix it.
