### ISSUE TITLE
Unable to transpile iOS release build

### ISSUE THREAD

**Issue by cobarx** [PeelTechnologies/react-native-tcp#24]
I'm getting a transpiler error when trying to build an iOS release build. For whatever reason this works fine with iOS debug builds and Android builds.

```
Unable to resolve module stream from /project_dir/node_modules/stream-browserify/node_modules/readable-stream/readable.js:
Module does not exist in the module map or in these directories:
/project_dir/node_modules/stream-browserify/node_modules,
/project_dir/node_modules
```

Any idea how I might resolve this? It looks like it might be related to needing the node stream module which React Native doesn't appear to have built in.

**Comment by cobarx** [comment]
This is with React Native 0.38 and react-native-tcp 3.0.1.

**Comment by aprock** [comment]
that's weird that it would specifically target ios release.  Is it possibly an npm cache issue?

You might try the workaround here
https://github.com/facebook/react-native/issues/4968

**Comment by lukasa1993** [comment]
no that does nothing, problem stays. + this version of problem doesn't look it to /Users it just can't find it

**Comment by aprock** [comment]
internally we're using [rn-nodeify](https://github.com/mvayngrib/rn-nodeify) to fixup any react-native packager issues.

here's the postinstall script
"postinstall": "rn-nodeify --install util,process,os,stream --hack"

**Comment by cobarx** [comment]
Yeah, wiping out node-modules didn't fix it.

I tried the rn-nodeify approach and get an error the moment it tries to import react-native-tcp:
```

**Comment by cobarx** [comment]
Yeah wiping out node_modules didn't fix it.

I tried the rn-nodeify method and the moment I attempt to import react-native-tcp, it causes the app to crash with the following error:
```
2016-11-30 10:46:32.019 [error][tid:com.facebook.react.JavaScript] Object prototype may only be an Object or null.
2016-11-30 10:46:32.021591 rn38[953:187127] Object prototype may only be an Object or null.
2016-11-30 10:46:32.025 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Object prototype may only be an Object or null.
2016-11-30 10:46:32.024763 rn38[953:187112] Unhandled JS Exception: Object prototype may only be an Object or null.
2016-11-30 10:46:32.029 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module (calling runApplication)
2016-11-30 10:46:32.029486 rn38[953:187127] Module AppRegistry is not a registered callable module (calling runApplication)
```

My index.ios.js is just:
```
import "./shim";
const net = require ("react-native-tcp");
```

**Comment by aprock** [comment]
is this a new project, or did you recently upgrade to RN 0.38.0?  if so did you run the react-native upgrade script?

**Comment by cobarx** [comment]
I've been testing in a brand new project so I could eliminate other variables from my existing one.

**Comment by aprock** [comment]
tracked this down, to a dependency problem in the react-native-tcp package.

In order for rn-nodeify's stream hack to work, we need to remove the dependency on stream-browserify.

The rctsockets example has been updated and tested. Can you try your builds with the streams branch? If it works I'll update the npm package.

**Comment by cobarx** [comment]
This is working great. 

Thanks so much for the quick turnaround time on this. We previously had separate native modules for doing our socket code in Java and Objective C and in the process of rewriting them in react-native-tcp I was able to address several longstanding bugs that were difficult to track down in native code. so I'm excited to get to release the new version to our team. It's so much nicer having a pure JS codebase and being able to debug the whole app in the Chrome Debugger. I really appreciate your work on this project.

**Comment by aprock** [comment]
awesome, glad to hear it. :)  I'll push out a new version presently

**Comment by aprock** [comment]
RN 3.0.2 has been published
