### ISSUE TITLE
Socket close event not raised in ioS

### ISSUE THREAD

**Issue by jmc420** [PeelTechnologies/react-native-tcp#29]
Hi

Thanks for fixing the listening issue (23). When I was testing the fix, I noticed another issue.

The socket close event is not raised when you listen for it on a socket accepted by a server in iOS - on an android device the event is raised fine.

The simple tcp server and client example contains an example of the problem:

https://github.com/jmc420/react-native-examples/blob/master/TcpServerProblem/README.md

See bin/ExampleTcpServer.js

let server = net.createServer((socket) => {
            console.log("New client");
            bus.sendMessage({ messageType: MessageType_1.default.CONNECTION_OPENED });
            socket.on("data", (data) => {
            });
            socket.on("close", () => {
                console.log("close client ");
                bus.sendMessage({ messageType: MessageType_1.default.CONNECTION_CLOSED });
            });
        }).listen(port);

The message console.log("close client") is never invoked.

James

**Comment by aprock** [comment]
@jmc420 thanks for finding this!
