### ISSUE TITLE
Builds fail when used with react-native-udp

### ISSUE THREAD

**Issue by joefocusrite** [PeelTechnologies/react-native-tcp#3]
I have a React Native project that has both this library and [react-native-udp](https://github.com/tradle/react-native-udp). It seems that the 'Run Script' stage of the iOS build seems to conflict when having the two projects together as they assume they're the only one using the project name

Taking device build from: .../Release-iphoneos
Taking simulator build from: .../Release-iphonesimulator
...I will output a universal build to: .../Release-universal
mkdir: .../Release-universal: File exists

XCode 7.3
react-native-tcp 1.0.1
react-native-udp 1.2.4

Strangely it's not a consistent repro. A clean build seems to work reliably.

**Comment by aprock** [comment]
I've updated the documentation and dependencies, this should work now.

**Comment by matto1990** [comment]
What was the fix for this? I can't see anything specific in the documentation about how to fix this issue.

**Comment by aprock** [comment]
@matto1990 are you seeing this issue again?  moving over to ```react-native link``` from cocoapods for build environment, seemed to fix it.

**Comment by matto1990** [comment]
This is a fresh project where I have only ever used `react-native link`.

I'm not certain where the dependency on your project is coming from. It seems to have come in when we addded `react-native-crypto`, which in turn meant adding `rn-nodeify`. I might look into if we actually need these libraries as we should only need the `crypto` part of `rn-nodeify`.

Thanks for the quick reply anyway!
