### ISSUE TITLE
3.0.6 xcode compile error

### ISSUE THREAD

**Issue by JasonMore** [PeelTechnologies/react-native-tcp#31]
Hi,

I noticed xcode is complaining about missing semi-colons here: https://github.com/PeelTechnologies/react-native-tcp/commit/ff3576578a18f27908b63ad3b824b9566924ae02#commitcomment-20414082

**Comment by aprock** [comment]
odd, maybe a merge error, i'll take a look

**Comment by aprock** [comment]
added semis, thanks
