### ISSUE TITLE
Can't Reload Without Error

### ISSUE THREAD

**Issue by cwbutler** [PeelTechnologies/react-native-tcp#33]
I am using this in a project and every time I reload the project in development I get an TCP error:

"socketDidDisconnect with nil clientDelegate for 0"
TcpSocketClient.m:247

What does this error mean exactly?
I am using an physical iPad device to develop on.

Is this because I do not destroy the connection before reload? If so, how to detect reload in react-native?

**Comment by aprock** [comment]
i'll take a look at this, the module itself should be handling the disconnect on reload.

**Comment by aprock** [comment]
i've made this into a warning instead of an error.  check out 3.1.0

**Comment by waymond91** [comment]
What does this warning mean?
