### ISSUE TITLE
Sending rapid commands hang

### ISSUE THREAD

**Issue by cwbutler** [PeelTechnologies/react-native-tcp#34]
This library seems to hang when sending rapid values to a tcp server.

I'm sending various buffer arrays and awaiting on response from a tcp server. Everything works fine... but then the client.write method hangs and never resolves the callback. From the documentation it seems that the data never finished sending from the client to the server. I'm not sure how to check to see if the data is still being sent or how to resend.

All I know is client.write seems to hang after rapidly sending values... once I destroy connection and reconnect... it resolves the issue.

I can use regular 'net' module in node just fine.

**Comment by aprock** [comment]
do not use this library for performance heavy operations. you might try out [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob).  They avoid the issues below by keeping everything native.

As a react-native native module there are several performance bottlenecks involved in marshaling data quickly across the native/javascript boundary.

1. react-native doesn't support sending data buffers across the bridge.  All data is encoded into Base64 strings and then decoded. more info: [RN Issue 1424](https://github.com/facebook/react-native/issues/1424)
2. all data is piped through a global shared device event queue. (RCTDeviceEventEmitter)

It's possible that moving to [RCTEventEmitter](https://github.com/facebook/react-native/commit/9ee1f37bade91d7db490cb3cb702104f268654ae) could improve your situation, as it is likely that events are getting dropped by RN.

**Comment by aprock** [comment]
update: RCTEventEmitter is simply a managing wrapper on top of RCTDeviceEventEmitter, so it's doubtful if it will improve your situation.

**Comment by cwbutler** [comment]
You're correct. I ended up writing a NativeModule to make a class around the CocoaAsyncSocket library.

Thanks for the knowledge.
