### ISSUE TITLE
Object prototype may only be an Object or null!

### ISSUE THREAD

**Issue by omidnavi** [PeelTechnologies/react-native-tcp#42]
Hi

I'm working on a project which needs tcp socket , and when i tried to use this library , i get the error mentioned in the title ! I know its a stream /rn-nodeify error , but while its a dependency of native-tcp , I posted this issue here , is there anything i can do to fix this one ?
react-native @0.41.2
react-native-net @3.2.1
rn-nodeify @7.0.1

![screenshot_2017-02-26-11-16-05](https://cloud.githubusercontent.com/assets/12028244/23338127/01290502-fc17-11e6-8fb4-bbf23c72835b.png)

**Comment by briman0094** [comment]
I'm getting this when trying to nodeify `zlib` for `react-native` as well. I haven't been able to find any information anywhere on this issue.

**Comment by briman0094** [comment]
I found a temporary workaround for this issue [here](https://github.com/mvayngrib/rn-nodeify/issues/32).

**Comment by nisargrthakkar** [comment]
I have also faced this error, after some workaround, I tried below steps and worked for me. Please check if this can help you as well.
1) Latest RN setup. (react-native init project_name)
2) `npm install react-native-tcp@3.1.0 --save`  (and other command as specified, only thing is to use 3.1.0 version )
3) update string-browserify and readable-stream to latest version
4) Manually add stream module to node_modules.

**Comment by zelll** [comment]
Try this:
> npm install react-native-tcp@3.2.1 --save
> npm install --save-dev rn-nodeify
> node_modules/.bin/rn-nodeify --install stream,process,util --hack
> npm install readable-stream@2.2.8 stream-browserify@2.0.1 --save

**Comment by viethaca** [comment]
@zelll  it's worked for me. thanks

**Comment by scriptfans** [comment]
same problem, how to fix it? thanks.

**Comment by omidnavi** [comment]
@scriptfans check this answer :

> Latest RN setup. (react-native init project_name)
npm install react-native-tcp@3.1.0 --save (and other command as specified, only thing is to use 3.1.0 version )
update string-browserify and readable-stream to latest version
Manually add stream module to node_modules.

if didnt work , check this one:
> npm install react-native-tcp@3.2.1 --save
npm install --save-dev rn-nodeify
node_modules/.bin/rn-nodeify --install stream,process,util --hack
npm install readable-stream@2.2.8 stream-browserify@2.0.1 --save

**Comment by scriptfans** [comment]
@omidnavi Thanks very much. I solved it in another way, we can install the github version rn-nodeify to fix it:
`
"devDependencies": {
    "rn-nodeify": "mvayngrib/rn-nodeify"
  }
`

**Comment by shiyunsheng** [comment]
@viethaca please help me 
it's worked for me when run debug.
When run release android, app has crashed
How did you solve it?

**Comment by shiyunsheng** [comment]
use the latest version .it's ok
npm install react-native-tcp --save
npm install --save rn-nodeify (no dev)
node_modules/.bin/rn-nodeify --install stream,process,util --hack
npm install readable-stream stream-browserify --save

**Comment by vietha2804** [comment]
@shiyunsheng i use rn 0.48.4 and react-native-tcp 3.3.0 and in package.json add

"scripts":{
    "postinstall": "rn-nodeify --install stream,process,util --hack",
  }

**Comment by uriva** [comment]
All the above not working for me. RN 0.55.4

**Comment by shiyunsheng** [comment]
@uriva use npm install readable-stream@2.2.8 stream-browserify@2.0.1 --save
