### ISSUE TITLE
Use self instead of this

### ISSUE THREAD

**Issue by joro** [PeelTechnologies/react-native-tcp#48]
Dear Sir/Madam,

I found an issue on TcpSocket.js file line 379 of master commit 6fa42c94386bd930cc780d7fa34b0feb0dfbd23a.

Sockets.write(this._id, str, function(err) {
    if (self._timeout) {
      self._activeTimer(this._timeout.msecs);
    }

The self variable is misspelled as this, which causes an error: null is not an object (evaluating 'this._timeout')

**Comment by dave-irvine** [comment]
There is a PR for this that needs merging https://github.com/PeelTechnologies/react-native-tcp/pull/53

**Comment by aprock** [comment]
merged
