### ISSUE TITLE
React Native 0.47 no longer supports createJSModules

### ISSUE THREAD

**Issue by cobarx** [PeelTechnologies/react-native-tcp#58]
React Native 0.47 removed createJSModules, so react-native-tcp will no longer compile on Android. See:
https://github.com/facebook/react-native/releases/tag/v0.47.0

I copied the fix from react-native-device-info to remove the `@Override` declaration, which allows it to work on RN 0.47, but I haven't tested it on older versions.

**Comment by cobarx** [comment]
I created a PR to address this:
https://github.com/PeelTechnologies/react-native-tcp/pull/57

**Comment by scriptfans** [comment]
+1 for this. please merge and release it, thanks.

**Comment by scriptfans** [comment]
when to release the new version?

**Comment by cobarx** [comment]
In the meantime, you can do:
`"react-native-tcp": "git+https://github.com/PeelTechnologies/react-native-tcp.git",`

It would be really nice to get a new release though.

**Comment by aprock** [comment]
sorry for the delay. 3.3.0 has been pushed to npm
