### ISSUE TITLE
undefined is not an object (evaluating 'Sockets.connect'

### ISSUE THREAD

**Issue by jay-cheung** [PeelTechnologies/react-native-tcp#6]
class pt extends Component {
    render() {
        return (
            <View style={styles.container}>
                <TouchableHighlight onPress={()=> {
                    var net = require('react-native-tcp');
                    var client = new net.Socket();
                    let options = {
                        host: '192.168.0.100',
                        port: 9100
                    };
                    client.connect(options, function () {
                        console.log('Connected');
                        client.write('Testing Print\n');
                    });

                }}>
                    <Text>Test</Text>
         </TouchableHighlight>
         </View>
        );
    }
}
The code running fine on IOS but report
"undefined is not an object (evaluating 'Sockets.connect')"
on android

**Comment by aprock** [comment]
which version are you testing?

**Comment by jay-cheung** [comment]
react-native 0.29

**Comment by aprock** [comment]
It looks like the linking steps are incorrect for android...
Can you try the following additional steps and see if this fixes it for you?

### Android

* Register and load the Native Module in your Main activity
([import](https://github.com/PeelTechnologies/react-native-tcp/blob/master/examples/rctsockets/android/app/src/main/java/com/rctsockets/MainActivity.java#L4), [getPackages](https://github.com/PeelTechnologies/react-native-tcp/blob/master/examples/rctsockets/android/app/src/main/java/com/rctsockets/MainActivity.java#L39))

```java
...

import com.peel.react.TcpSocketsModule;     // <--- import //

public class MainActivity extends ReactActivity {
	...

  /**
   * A list of packages used by the app. If the app uses additional views
   * or modules besides the default ones, add more packages here.
   */
  @Override
  protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new TcpSocketsModule()           // <- add here
      );
  }
}
```

**Comment by wean** [comment]
In the version 0.29.2, this function(getPackages) is moved to MainApplication.java

**Comment by aprock** [comment]
thanks @wean, I'll test that out.

**Comment by aprock** [comment]
updated the docs and sample code for 0.29.2.
https://github.com/PeelTechnologies/react-native-tcp/pull/7
