### ISSUE TITLE
Server on iOS refuses all connections

### ISSUE THREAD

**Issue by acb** [PeelTechnologies/react-native-tcp#72]
I've been testing on an an iPad 2 running iOS 9.3.5 and hosting a server through `TCP.createServer()` doesn't seem to work.  Every time I attempt to connect to it with another device I get "Connection refused", and as far as I can tell no event gets triggered on the iOS host -- neither the `data` or `error` events fire.

What's strange is that it works as a client.  If I have an Android device host then the iOS device can connect as a client just fine.

Am I missing something about how to make a host work on iOS?

**Comment by acb** [comment]
@aprock sorry to ping you but based on the commit history you probably know more about this module than anyone else. Do you know off the top of your head why my iOS servers wouldn't be able to accept any incoming connections?

**Comment by x3388638** [comment]
I have the same problem
while the Android device try to connect ( `net.connet()` ) to iOS device ( `net.createServer()` ), it will show error that `fail to connect to /xxx.xxx.xxx.xxx (port xxxxx): isConnected failed: ECONNREFUSED (Connection refused)`
if both the devices are Android, it works

**Comment by x3388638** [comment]
I solve this problem by listening to specific host
```
const server = net.createServer(() => { /* ... */ });
server.listen(PORT, HOST);
```

**Comment by acb** [comment]
@x3388638 thanks for the tip, I was able to get the server to respond by setting the host IP address.

I'm now having issues where `socket.write` just stops working, I can send a few packets through it (2 or 3), and then `socket.write` stops sending anything across the socket.  Have you run into that at all or is it just me?  There's no error or anything, it's just that `socket.write` never sends anything to the connected client.

The exact same code runs just fine on Android, it never has issues with `socket.write`.

**Comment by x3388638** [comment]
@acb I don't have the problem that `socket.write` stops working.
However, you can try to create a new tcp connection to send (`write` or `pipe`) a single data object and then close the connection.
As a result the `write` will be called once for each connection, and it will be easy to combine the data chunks if the data is too large to send in a single packet.

create a new connection to send data:
```
const { Readable } = require('stream');
const socket = net.connect(PORT, IP, () => {
	if (YOU_WANT_TO_USE_WRITE_FUNCTION) {
		socket.write(new Buffer('YOUR DATA'));
		socket.end();
	} else {
		const stream = new Readable();
		stream.push(new Buffer('YOUR DATA'));
		stream.push(null);
		stream.pipe(socket);
	}
});
```

receive and combine data:
```
const server = net.createServer((socket) => {
	const chunks = [];

	socket.on('close', () => {
		const dataBuffer = Buffer.concat(chunks);
		// parse the buffer
	});

	socket.on('data', (data) => {
		chunks.push(data);
	});
});
```

some reference:
https://medium.freecodecamp.org/node-js-streams-everything-you-need-to-know-c9141306be93
https://stackoverflow.com/questions/36397950/how-to-send-file-over-tcp-in-one-time-in-nodejs

**Comment by acb** [comment]
@x3388638 Thanks for the tip, I refactored my code a bit and it made loading a large amount of data much faster.

I hate to bother you since you're not a maintainer of this project, but I am learning a little more about why my `socket.write` stops working.  Maybe you can point me in the right direction since you've been so helpful so far 😄 

I have 2 different kinds of connections in my app, one that sends a large amount of data and then closes, and then a long-lived connection that occasionally sends small packets of data.  Your code snippet above helped my improve my large data single connection, but the long-lived connection is the one that's having issues with `socket.write`.

To keep the long-lived connection around I store it in Redux so that I can easily dispatch actions to send messages.  On Android this works perfectly, but on iOS I can only send 1 packet through my socket before `socket.write` stops sending.  A client that's connected on that socket can keep sending data across it but when the server goes to `write` nothing ever appears on the client (after that 1st packet that works).  It's almost as though the socket gets blocked for writing after that 1st write...is there any command or character flag that you're aware of that maybe needs to get passed through the socket to indicate that it's ready to be written to again?

I don't want to have to terminate and refresh the connection every time the client wants to communicate because it's super inefficient and the whole point of sockets is that you're supposed to be able to leave them open and stream data as you need.

Thanks, and again sorry to bug you about this!

**Comment by x3388638** [comment]
@acb Sorry that I have no idea how to help you.
Before I refactor my app to use the above snippet I mentioned, there is only a long-lived tcp connection between each device to transfer data, but I didn't encounter the problem about `socket.write`. 

I think the most different work flow is that I used `global` to store the `socket` object rather than Redux, therefore I could use something like `global.users[ip].socket.write()` to write data.

However, I have a problem is that I can't send a large (about a base64 string encoded from a picture took by a modern smart phone) data from Android to other device, but it works on iOS. The large data will be divided in many chunks by TCP, but the Android device doesn't send all parts of chunks.
Do you have the same problem or any ideas? Thanks!

**Comment by acb** [comment]
@x3388638 no worries, it's a pretty weird problem.  I found someone using the base library for iOS that has the same problem as me so hopefully we can figure it out there (https://github.com/robbiehanson/CocoaAsyncSocket/issues/613).

I haven't had any issues with chunks not getting received on Android, but I did have a problem with the `close` callback not getting triggered on the client sometimes.  In my case though I knew I was sending JSON data so I did this:

Server
```
let data = JSON.stringify(<lots of data>);
socket.write(new Buffer(data));
socket.end();
```

Client
```
let chunks = [];
client.on('data', (data) => {
    chunks.push(data);
    const message = Buffer.concat(chunks);
    // manually forces the end handler to trigger in case it doesn't on its own
    try {
        data = JSON.parse(message.toString());
        client.end();
    } catch (e) { // ignore if not JSON
    }
});
```

Not sure if that will help your case, but it's the best I've got.

**Comment by x3388638** [comment]
@acb Thanks a lot, but it doesn't work.
I have created an issue for the problem.
