### ISSUE TITLE
Error: package com.peel.react does not exist

### ISSUE THREAD

**Issue by rinlevan** [PeelTechnologies/react-native-tcp#80]
F:\dev\NearChat\android\app\src\main\java\com\reactnativesocketioexample\MainApplication.java:7: error: package com.peel.react does
not exist
import com.peel.react.TcpSocketsModule;
                     ^
F:\dev\NearChat\android\app\src\main\java\com\reactnativesocketioexample\MainApplication.java:29: error: cannot find symbol
            new TcpSocketsModule()
                ^
  symbol: class TcpSocketsModule
2 errors

I got some issue while building project with react-native-tcp.
How to fix it? thanks

**Comment by rhyswilliams0** [comment]
For future weary googlers:

Add `compile project(':react-native-tcp')` to app/build.gradle.
