### ISSUE TITLE
Error building on react-native 30 after running rnpm link

### ISSUE THREAD

**Issue by carbureted** [PeelTechnologies/react-native-tcp#9]
```
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-tcp : Configuration with name 'default' not found.
```

My build.gradle is pretty vanilla:

```
dependencies {
    ...
    compile project(':react-native-tcp')
    ...
}
```

Possibly a similar issue? https://github.com/lelandrichardson/react-native-maps/issues/288

Thanks!

**Comment by aprock** [comment]
Can you verify that your settings.gradle is similar to the one in the rctsockets [example](https://github.com/PeelTechnologies/react-native-tcp/blob/master/examples/rctsockets/android/settings.gradle#L5)?

**Comment by chaitanyaK84** [comment]
I am also getting the same error 
--
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-tcp : Configuration with name 'default' not found.
--

Following is the content of settings.gradle
--
rootProject.name = 'test'

include ':app'
include ':react-native-tcp'
project(':react-native-tcp').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-tcp/android')
include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(settingsDir, '../node_modules/react-native-image-picker/android')
--

Please guide me to resolve this issue. Thanks.

**Comment by chetansaundankar** [comment]
We were facing same issue, here is how we solved it:

- Clone react-native-tcp, build an aar file
- Create a folder named `libs` in the app directory of your react native project's android directory and place the aar file in that folder
- In build.gradle of app of your react native project, remove `compile project(':react-native-tcp')`; add  `compile(name:'reactnativetcp',` ext:'aar')` and `compile 'com.koushikdutta.async:androidasync:2.1.6'`
- In your react-native app's android project's build.gradle add following to `allprojects.repositories` configuration

        flatDir {
            dirs 'libs'
        }

**Comment by aprock** [comment]
@chetansaundankar what version of the android build tools are you using?

**Comment by aprock** [comment]
Should be fixed by using the react-native link command over the rnpm link command.
