### ISSUE TITLE
Invariant Violation : Native module cannot be null

### ISSUE THREAD

**Issue by StevenB45** [PeelTechnologies/react-native-tcp#90]
Hello,

 I have a problem only on iOS (working on Android).
![sans titre](https://user-images.githubusercontent.com/28841322/47503333-1ed1d080-d86a-11e8-8f57-2d113b3988f3.jpeg)
Any idea?

Thank you.

**Comment by dominikweifieg** [comment]
react-native link react-native-tcp does not add libTcpSockets.a to Linked Frameworks and Libraries. Doing so manually solves the issue.

**Comment by StevenB45** [comment]
I had to unlink before and now it works, thank you!

**Comment by alex-miller-0** [comment]
Thanks, manual linking (i.e. following [these](https://facebook.github.io/react-native/docs/linking-libraries-ios.html) steps) solved the issue for me.

This should be used instead of the answers in #1
